name: phoenix_wings
description: Phoenix Channel client for Dart
version: 0.2.1
author: mfeckie<mfeckie@gmail.com>
homepage: https://github.com/mfeckie/phoenix_wings

dev_dependencies:
  dartdoc: "0.29.2"
  test: "1.9.4"
  mockito: "^4.1.1"
  stream_channel: "2.0.0"
  intl: "^0.16.0"

environment:
  sdk: '>=2.2.0 <3.0.0'
